name: Full CI/CD Pipeline

on:
  push:
    branches:
      - ci_cd  # Trigger on pushes to main branch
  pull_request:
    branches:
      - ci_cd  # Trigger on pull requests to main branch

jobs:
  backend-build:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'  # Python version

    - name: Install backend dependencies
      run: |
        cd server  # Adjust this to your backend folder
        python -m pip install --upgrade pip
        pip install setuptools
        pip install git+https://github.com/ageitgey/face_recognition_models
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        cd server
        pytest tests/  # Run tests in the backend tests/ folder

  frontend-build:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    needs: backend-build  # Wait for the backend build to complete

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use appropriate Node version

    - name: Install frontend dependencies
      run: |
        cd frontend  # Adjust to your frontend folder
        npm install
        npm install @testing-library/react @testing-library/jest-dom jest react-router-dom

    - name: Run frontend tests
      run: |
        cd frontend
        npm test  # Run Jest or other test suite

    - name: Build frontend
      run: |
        cd client-app
        npm run build  # Create production build of the frontend

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]  # Wait for both builds to complete

    steps:
    - name: Deploy to server (placeholder)
      run: echo "Deploying both frontend and backend..."  # Customize deployment process here
